---
- name: Ping test to the localhost.

  hosts: LocalHost
  connection: local
  
  tasks:
  
  - name: Verify connectivty
    ping:
    
  - name: Check current user
    command: whoami
    register: whoami
    
  - debug: var=whoami.stdout_lines

- name: Create new file

  hosts: LocalHost
  connection: local
  
  become: yes
  become_user: root
  
  tasks:
 
  - name: Creating text file
    file:
     path: /etc/delta.txt
     content: "Hello World"
     state: touch
     mode: u=rw,g=r,o=rwx
