---
- name: Ping test to the localhost.

  hosts: LocalHost
  connection: local
  
  tasks:
  
  - name: Verify connectivty
    ping:
    
  - name: Check current user
    command: whoami
    register: whoami
    
  - debug: var=whoami.stdout_lines

- name: Create new file
